# Site settings
timezone: Asia/Shanghai

title: "思行文道"
header-img: "images/facebook.jpg"
tagline: "cn"  
description: "Mars & 林久久|思而行，文之道"
baseurl: ""
url: "http://mars99.space"  

github_username: "marswoo"
gavatar: "http://dreamofbook.qiniudn.com/Az..png"
favicon: "images/favicon.png"

owner: 
  name: "Mars & 林久久"
  email: "wudi.xjtu@gmail.com"
  bio: ""

url: "http://marswoo.github.io"
feed: "/atom.xml"
author_info: "<a href='http://marswoo.github.io/'>思行文道</a>"

markdown: "kramdown"
highlighter: "pygments"
permalink: "pretty"
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
relative_permalinks: true

pages: ["about.md", "99.md", "mars.md", "tags.md"]

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "marswoo"
      header-img: "images/facebook.jpg" # We don't want posts without a header image, that whould mean white on white


auto: true
server: true
permalink: none
baseurl: ""

prose:
  rooturl: "_posts"
  # siteurl: "http://liyu1981.github.io/"
  media: "images"

  metadata:
    "_posts/blog": |
      title:    "Title of your article"
      abstract: "Abstract"
    "_posts/projects": |
      name: "Project Name"
      img:  "Project Thumbnail"
